# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker://duffn/python-poetry:3.8-slim
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run package creation
      run: |
        cd ../..
        ls
        poetry build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: v0.1.0
        files: |
          dist/
    - name: executing ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm -rf tec_api
          git clone git@github.com:abajorat/tec_api.git
          cd tec_api
          poetry install
          uvicorn tec_api.main:app --host 0.0.0.0 --reload